---
# Run unit tests and coverage report for pull requests

name: Run Nox Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies using nox
        run: |
          python -m pip install --upgrade pip
          pip install nox

#      - name: Harden runner for security
#        uses: step-security/harden-runner@v1

      - name: Run coverage session with Nox
        run: |
          nox -s coverage_xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
