---
# Run unit tests and coverage report for pull requests

name: Dependency Security Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-scan:
    name: Run Dependency Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.11  # Use your project's Python version

      - name: Install Dependencies for Scans
        run: |
          python -m pip install --upgrade pip
          pip install uv pip-audit
#          pip install safety pip-audit

# safety has deprecated the `check` command and `scan` requires login
# Will need to evaluate how to do that in a GHA workflow
#      - name: Run Safety Scan
#        run: |
#          if [ -f requirements.txt ]; then
#            safety check -r requirements.txt
#          else
#            echo "No requirements.txt file found. Skipping Safety scan."
#          fi

      - name: Run pip-audit Scan
        run: |
          uv pip compile pyproject.toml --output-file requirements.txt
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping pip-audit scan."
          fi
